### ISSUE TITLE
avro-kafkajs and schema-registry-api don't support AVRO encoded key

### ISSUE THREAD

**Issue by Dieken** [ovotech/castle#12]
@kafkajs/confluent-schema-registry supports AVRO encoded key but doesn't support extra options for avro.Type.forSchema() function,   @ovotech/avro-kafkajs supports extra options but no AVRO encoded key :-(

**Comment by ivank** [comment]
@Dieken We never needed it ourselves so I put off implementing it until it was actually needed. Since there appears to be some interest in it, I've tried to implement it now in a PR.


(Taken from the examples) Using `ovotech/avro-kafkajs` you can do it transparently:
https://github.com/ovotech/castle/blob/5d3541d77046b3c3599ecd07b005672d502cf365/packages/avro-kafkajs/examples/encoded-key.ts#L37-L45

https://github.com/ovotech/castle/blob/5d3541d77046b3c3599ecd07b005672d502cf365/packages/avro-kafkajs/examples/encoded-key.ts#L51-L57

Or using the low level functions:
https://github.com/ovotech/castle/blob/5d3541d77046b3c3599ecd07b005672d502cf365/packages/avro-kafkajs/examples/schema-registry.ts#L35-L41

https://github.com/ovotech/castle/blob/5d3541d77046b3c3599ecd07b005672d502cf365/packages/avro-kafkajs/examples/schema-registry.ts#L47-L56

Would that help you out?

**Comment by Dieken** [comment]
Sorry I didn't notice your prompt response,   I just verified #13 , it works as expected, thank you very much for your detailed examples!

Waiting for this new 0.2.0 release 👍

**Comment by Dieken** [comment]
Btw,  explain a little why I need AVRO encoded key,  just like your example,  I have a simple AVRO record "account":

```
record Account {
      long id;
}
```

Avro is very smart to encode to only a long integer, no extra overhead at all,  my code also looks more intuitive, it uses an "account" object as key, not just a number, and I can extend the account record without breaking backward compatibility.

**Comment by ivank** [comment]
Well Kafka js always returns a Buffer. I didn't find a way to get if the key is encoded or not so I can decode it. I'm reluctant to rely on exceptions (attempt to decode and catch exceptions kinda thing). 
Can you describe a bit more your example and how you would use it?
If we can not rely on "encodedKey" flag that would be awesome!

**Comment by Dieken** [comment]
I already updated my local code to use the new feature, although it works,  it indeed looks a little ugly the special "encodedKey" flag, but I think that's inevitable,   maybe move the flag to `AvroKafka.consumer()`?  Anyway, I don't mind much.

In my example,  I have message key/value pair  `<Account, Transaction>`，the definition of `Account` is shown in the last comment,  I use a complex type to wrap an integer ID to make the meaning of message key clear,  and I can also extend the key type without breaking backward compatibility.

Event the key is simple integer or string, I would like to encode it in AVRO and store into schema registry,  that makes my message keys and values are both managed by schema registry.
