### ISSUE TITLE
avro-ts Typescript Enum Support

### ISSUE THREAD

**Issue by arminhaghi** [ovotech/castle#124]
In avro-ts AVRO enums are only converted to string unions. I'm not sure the exact reason for this, but I was looking for a way to use Typescript enums instead.

For example 
```
{
  "name": "com.example.avro.MyEnum",
  "type": "enum",
  "symbols": ["ACTIVE", "INACTIVE"]
}
```
will be converted to
```
export type ComExampleAvroMyEnum = "ACTIVE" | "INACTIVE";
```
With Typescript enums it will be converted to
```
export enum ComExampleAvroMyEnum {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}
```

**Comment by ivank** [comment]
I'm really not fan of TS Enums in general as they force the code to _always_ use the enums, rather than the underlying labels.
 
Every time I've said to myself "this is a classic place for an enum" and used them I've regretted them later.
Maybe const enums are a bit better but still ... you want to place `"ACTIVE"` but no, you need to import this from the types. And if you need to supply the value from somewhere else (like a database or something) you're forced to write converters from one enum to another or string values to enums all over the place ... and maintain them. Even if `"ACTIVE"` will be the same as `ComExampleAvroMyEnum.ACTIVE`, to TS those are totally different values (and rightfully so). 

So yeah string literal unions are much more flexible.

Do you have a specific use case where you think those are superior? I'd love to be proven wrong.

**Comment by arminhaghi** [comment]
Thanks @ivank, you have successfully made me question my choices now 😄. I agree with what you said, however I think syntax preference is also involved. While in this case one has arguable benefits over the other some folks might still prefer to use enums. That's why in my [pull request](https://github.com/ovotech/castle/pull/125) I made it optional.

Here are some reasons enums could be considered "superior" than unions, but those are mostly in general and not necessarily applicable here because how Avro enums are handled in [avsc](https://www.npmjs.com/package/avsc) so it doesn't apply to this package either.

1. Enums are iterable while string unions aren't.
2. If the underlying value needs to be changed, you'd only need to change it in one place rather than a full find&replace.
3. Enums could have static methods.
4. Numeric enums could be used in comparison in a more expressive way. For example,
```
enum Status {
  NEW = 1,
  COMPLETED = 5
}
```
`if (foo.status > Status.NEW)` rather than `if (foo.status > 1)`

**Comment by ivank** [comment]
Fair enough - its a very minimal change and if it makes your life easier, and doesn't affect anything else, then I'm all for it! 

But yeah just a bit fo unsolicited advice - every time I've went with enums it bit me in the posterior later :-D

**Comment by arminhaghi** [comment]
Thanks yeah, for sure I'll be thinking about union types in my next project.

**Comment by arminhaghi** [comment]
@ivank I see the MR is merged, but the packages haven't published yet. Can you confirm when they will be published to npm?

**Comment by ivank** [comment]
It seems you've added avsc of your company's artifactory, which is not publicly available - since its dev dep I just put it back to the version the rest of the code is using (even if its a bit outdated)

**Comment by arminhaghi** [comment]
My bad, thanks for fixing and pushing it.
